---
- name: Print out a debug message
  hosts: all
  gather_facts: no
  become: no


  vars:
    __message: Hello!


  tasks:
    - name: Print debug message
      debug:
        var: __message


...
