---
- name: Create inventory based on passed extra_vars
  hosts: all
  gather_facts: no
  become: no


  vars_files:
    - vars/defaults.yml


  vars:
    provision_host: "{{ tower_provision_host | default(ansible_play_hosts | random) }}"


  tasks:
    - name: "Create in-memory inventory for {{ provision_host }}"
      add_host:
        name: "{{ provision_host }}"
        groups:
          - remdiation
      delegate_to: localhost


# =========================================================================== #


- name: Remove file from hosts
  hosts: remdiation
  gather_facts: no
  become: no


  vars_files:
    - vars/defaults.yml


  tasks:
    - name: "Remove file from {{ inventory_hostname }}"
      file:
        path  : "{{ check_file }}"
        state : absent


...
