---
- name: Run a series of tasks, with exception handling, on a given host
  hosts: localhost
  gather_facts: no
  become: no


  tasks:
    - name: Debug Gitlab Webhook
      debug:
        msg:
          - "{{ __message | default('Not defined', True) }}"
          - "{{ tower_webhook_payload.event_name | default('Not defined', True) }}"
          - "{{ tower_webhook_payload.checkout_sha | default('Not defined', True) }}"
          - "{{ tower_webhook_payload.commits.message | default('Not defined', True) }}"
          - "{{ tower_webhook_payload.commits.added | default('Not defined', True) }}"
          - "{{ tower_webhook_payload.commits.modified | default('Not defined', True) }}"


...
