---
- name: Run a series of tasks, with exception handling, on a given host
  hosts: localhost
  gather_facts: no
  become: no


  tasks:
    - name: Debug Gitlab Webhook
      debug:
        msg:
          - "{{ __message                              | default('Not defined', True) }}"
          - "{{ tower_webhook_payload.[0]event_name       | default('Not defined', True) }}"
          - "{{ tower_webhook_payload.[0]checkout_sha     | default('Not defined', True) }}"
          - "{{ tower_webhook_payload.[0]commits.message  | default('Not defined', True) }}"
          - "{{ tower_webhook_payload.[0]commits.added    | default('Not defined', True) }}"
          - "{{ tower_webhook_payload.[0]commits.modified | default('Not defined', True) }}"


...
