---
- name: Launch specified job template
  hosts: localhost
  connection: local
  gather_facts: no
  become: no


  vars_files:
    - vars/job_launch_inmem_test.yml


  tasks:
    - include_role:
        name: redhat_cop.tower_configuration.job_launch


...
