---
- name: Long running job test
  hosts: all
  gather_facts: no
  become: no


  vars:
    pause_time    : 60
    num_retries   : 1440
    poll_interval : 3

    check_commands:
      - uname -a
      - uptime
      - ping -c 1 127.0.0.1


  tasks:
  - name: Include long_running_tasks.yml
    include_tasks: tasks/long_running_tasks.yml


...
