---
- name: Long running job test
  hosts: all
  gather_facts: no
  become: no


  vars:
    time_to_sleep: 30


  tasks:
    - name: Simulate a long running job
      command: "sleep {{ tower_time_to_sleep | default(time_to_sleep) | default(10) }}"
      async: "{{ time_to_sleep + 10 }}"   # give +10s leeway
      poll: 3


...
