---
- name: Long running job test
  hosts: all
  gather_facts: no
  become: no


  vars:
    time_to_sleep: 300


  tasks:
    - name: Simulate a long running job
      command : "sleep {{ time_to_sleep }}"
      async   : "{{ time_to_sleep + 10 }}" # give +10s leeway
      poll    : 3


...
