---
- name: Split up hosts into single job runs
  hosts: all
  become: no
  gather_facts: no


  vars_files:
    - vars/defaults.yml


  tasks:
    - name: Launch job per each host
      no_log : "{{ __no_log | default('yes') }}"
      uri    :
        url              : "{{ tower_remdiation_workflow }}"
        force_basic_auth : yes
        user             : "{{ tower_user }}"
        password         : "{{ tower_password }}"
        body_format      : json
        method           : POST
        status_code      : 201
        body:
          extra_vars:
            tower_provision_host: "{{ item }}"
      loop: "{{ ansible_play_hosts }}"
      run_once: yes


...
